version: "3"

name: "secobserve_prod"

volumes:
  prod_mysql_data:

networks:
  traefik:
  database:

services:

  traefik:
    image: "traefik:v3.0"
    container_name: "prod_traefik"
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=secobserve_prod_traefik"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.traefik-ipallowlist.ipallowlist.sourcerange=172.18.0.1/24"
      # - "traefik.http.routers.api.middlewares=traefik-ipallowlist@docker"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default
      - traefik

  frontend:
    image: maibornwolff/secobserve-frontend:0.9.10
    container_name: "prod_secobserve_frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`secobserve.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    environment:
      API_BASE_URL: ${SO_API_BASE_URL:-http://secobserve-backend.localhost/api}
      OAUTH2_ENABLE: ${SO_OAUTH2_ENABLE:-false}
      OAUTH2_AUTHORITY: ${SO_OAUTH2_AUTHORITY:-dummy}
      OAUTH2_CLIENT_ID: ${SO_OAUTH2_CLIENT_ID:-dummy}
      OAUTH2_REDIRECT_URI: ${SO_OAUTH2_REDIRECT_URI:-http://secobserve.localhost}
      OAUTH2_POST_LOGOUT_REDIRECT_URI: ${SO_OAUTH2_POST_LOGOUT_REDIRECT_URI:-http://secobserve.localhost}
      OAUTH2_SCOPE: ${SO_OAUTH2_SCOPE:-dummy}
    networks:
      - traefik

  backend:
    image: maibornwolff/secobserve-backend:0.9.10
    container_name: "prod_secobserve_backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`secobserve-backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
    depends_on:
      - mysql
    environment:
      # --- Admin user ---
      ADMIN_USER: ${SO_ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${SO_ADMIN_PASSWORD:-admin}
      ADMIN_EMAIL: ${SO_ADMIN_EMAIL:-admin@example.com}
      # --- Database ---
      DATABASE_ENGINE: ${SO_DATABASE_ENGINE:-django.db.backends.mysql}
      DATABASE_HOST: ${SO_DATABASE_HOST:-mysql}
      DATABASE_PORT: ${SO_DATABASE_PORT:-3306}
      DATABASE_DB: ${SO_DATABASE_DB:-secobserve}
      DATABASE_USER: ${SO_DATABASE_USER:-secobserve}
      DATABASE_PASSWORD: ${SO_DATABASE_PASSWORD:-secobserve}
      # --- Security ---
      ALLOWED_HOSTS: ${SO_ALLOWED_HOSTS:-secobserve-backend.localhost}
      CORS_ALLOWED_ORIGINS: ${SO_CORS_ALLOWED_ORIGINS:-http://secobserve.localhost}
      DJANGO_SECRET_KEY: ${SO_DJANGO_SECRET_KEY:-NxYPEF5lNGgk3yonndjSbwP77uNJxOvfKTjF5aVBqsHktNlf1wfJHHvJ8iifk32r}
      FIELD_ENCRYPTION_KEY: ${SO_FIELD_ENCRYPTION_KEY:-DtlkqVb3wlaVdJK_BU-3mB4wwuuf8xx8YNInajiJ7GU=}
      # --- OAuth2 ---
      OAUTH2_AUTHORITY: ${SO_OAUTH2_AUTHORITY:-}
      OAUTH2_USERNAME: ${SO_OAUTH2_USERNAME:-}
      OAUTH2_FIRST_NAME: ${SO_OAUTH2_FIRST_NAME:-}
      OAUTH2_LAST_NAME: ${SO_OAUTH2_LAST_NAME:-}
      OAUTH2_EMAIL: ${SO_OAUTH2_EMAIL:-}
    networks:
      - traefik
      - database

  mysql:
    image: mysql:8.1.0
    container_name: "prod_mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${SO_MYSQL_RANDOM_ROOT_PASSWORD:-yes}
      MYSQL_DATABASE: ${SO_MYSQL_DATABASE:-secobserve}
      MYSQL_USER: ${SO_MYSQL_USER:-secobserve}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secobserve}
    volumes:
      - prod_mysql_data:/var/lib/mysql
    networks:
      - database
